development:
  adapter: solr
  url: <%= ENV['SOLR_DEVELOPMENT_URL'] || "http://127.0.0.1:8983/solr/hydra-development" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || "http://127.0.0.1:8985/solr/hydra-test" %>
production:
  adapter: solr
  url: http://127.0.0.1:8983/solr/cypripedium
